packages:
  hal: !include
    file: heltec_lora32_v2_hal.yaml
  resources: !include
    file: resources.yaml
  version: !include
    file: version.yaml

external_components:
  - source: 
      type: git
      url: https://github.com/IoTLabs-pl/ESPHome-Components
      ref: v1.0.0
    components:
      - wmbus_common
      - wmbus_radio
      - wmbus_meter
  - source: 
      type: git
      url: https://github.com/IoTLabs-pl/wM-Bus-Gateway
      ref: ${wmbus_gateway_version}
    components:
      - wmbus_gateway

esphome:
  name: wmbus-gateway
  friendly_name: wM-Bus Gateway
  comment: wM-Bus Gateway for ESPHome
  project:
    name: IoTLabs.wM-Bus Gateway
    version: ${wmbus_gateway_version}

wmbus_radio:
  radio_type: SX1276
  cs_pin: GPIO18
  reset_pin: GPIO14
  irq_pin: GPIO35
  on_frame:
    - then:
        - repeat:
            count: 20
            then:
              - light.control:
                  id: status_led_
                  state: !lambda return iteration % 2 == 0;
              - delay: 50ms

wmbus_gateway:
